# Generated by Django 2.0.6 on 2018-07-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
